name: Newbie Media Design
favicon: null
layout_spectrum: 0.7328269130084664
typography_spectrum: 0.8685712167061865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.41565970284864306
  lightness: 0.403916327515617
  saturation: 0.8621031048242003
  rhythmicContrast: 0.1026374779175967
purpose: []
