name: Newbie Media Design
favicon: null
layout_spectrum: 0.79043
typography_spectrum: 0.26203
title: Newbie Media Design Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#3d3e43'
    - '#3f7fb6'
    - '#b8dbec'
  brandStrength: 1
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0.1026374779175967
purpose: []
